{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5372ffb6-93e6-427b-8294-f20b2fc9b82d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
    "from datasets import load_dataset\n",
    "from torch.utils.data import DataLoader\n",
    "import numpy as np\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "2541aa0a-d58c-4337-a265-61fb34dfe098",
   "metadata": {},
   "outputs": [],
   "source": [
    "def set_seed(seed=42):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    torch.cuda.manual_seed_all(seed)\n",
    "    # GPUの演算（CuDNN）を確定的にする設定\n",
    "    torch.backends.cudnn.deterministic = True\n",
    "    torch.backends.cudnn.benchmark = False\n",
    "\n",
    "set_seed(42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2710cd36-757a-413b-b4a7-0efa1d5608f4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "71bb4932e3734f5a95c623157dbd9c00",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# 1. モデルとトークナイザーの準備\n",
    "model_name = \"Qwen/Qwen3-1.7B\"\n",
    "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "model = AutoModelForCausalLM.from_pretrained(\n",
    "    model_name,\n",
    "    dtype=\"auto\",\n",
    "    device_map=\"auto\"\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b4330ab7-9d5d-4701-89f7-9eca30fde651",
   "metadata": {},
   "outputs": [],
   "source": [
    "class SparseAutoencoder(nn.Module):\n",
    "    def __init__(self, d_in, d_sae, l1_coeff):\n",
    "        super().__init__()\n",
    "        self.d_in = d_in\n",
    "        self.d_sae = d_sae\n",
    "        self.l1_coeff = l1_coeff\n",
    "\n",
    "        # Encoder: 入力を高次元に投影し、ReLUで活性化\n",
    "        self.encoder = nn.Linear(d_in, d_sae)\n",
    "        # 最初は入力信号のみに反応し、その後の学習（L1正則化）によって、不要なユニットが自然に負のバイアスを持ってオフになっていく\n",
    "        self.encoder.bias.data.zero_()\n",
    "\n",
    "        # Decoder: 高次元から元の次元へ復元\n",
    "        self.decoder = nn.Linear(d_sae, d_in, bias=False)\n",
    "        # 初期状態でデコーダの重みのノルムを1に設定\n",
    "        self.set_decoder_norm_to_unit()\n",
    "\n",
    "        # 入力の平均を引くためのバイアス（オプションだが精度向上のため推奨）\n",
    "        self.b_dec = nn.Parameter(torch.zeros(d_in))\n",
    "\n",
    "    def set_decoder_norm_to_unit(self):\n",
    "        \"\"\"デコーダの各列（各特徴量ベクトル）のL2ノルムを1に固定する\"\"\"\n",
    "        with torch.no_grad():\n",
    "            # dim=0（行方向）で計算し、各列の長さを1にする\n",
    "            norm = torch.norm(self.decoder.weight, dim=0, keepdim=True)\n",
    "            self.decoder.weight /= norm\n",
    "\n",
    "    def forward(self, x):\n",
    "        # 1. 中心化（デコーダバイアスを引く）\n",
    "        x_centered = x - self.b_dec\n",
    "\n",
    "        # 2. エンコード（スパースな特徴量 f の抽出）\n",
    "        # f = ReLU(W_enc * x + b_enc)\n",
    "        f = F.relu(self.encoder(x_centered))\n",
    "\n",
    "        # 3. デコード（再構成）\n",
    "        # x_hat = W_dec * f + b_dec\n",
    "        x_reconstruct = self.decoder(f) + self.b_dec\n",
    "\n",
    "        # 4. 損失の計算\n",
    "        # 再構成誤差 (MSE)\n",
    "        reconstruction_loss = F.mse_loss(x_reconstruct, x)\n",
    "        # スパース性ペナルティ (L1)\n",
    "        l1_loss = self.l1_coeff * f.sum(dim=-1).mean()\n",
    "\n",
    "        loss = reconstruction_loss + l1_loss\n",
    "\n",
    "        return x_reconstruct, loss, f"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d344f0ce-0fdb-4b45-aba1-bae518ebb363",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting activations from LLM...\n",
      "Starting SAE Training...\n",
      "Epoch 0: Loss 1.019018\n",
      "Epoch 1: Loss 0.605705\n",
      "Epoch 2: Loss 0.539378\n",
      "Epoch 3: Loss 0.507102\n",
      "Epoch 4: Loss 0.488419\n",
      "Epoch 5: Loss 0.475911\n",
      "Epoch 6: Loss 0.466383\n",
      "Epoch 7: Loss 0.458965\n",
      "Epoch 8: Loss 0.451606\n",
      "Epoch 9: Loss 0.445174\n",
      "Epoch 10: Loss 0.440361\n",
      "Epoch 11: Loss 0.436454\n",
      "Epoch 12: Loss 0.433318\n",
      "Epoch 13: Loss 0.430043\n",
      "Epoch 14: Loss 0.426807\n",
      "Epoch 15: Loss 0.423414\n",
      "Epoch 16: Loss 0.419902\n",
      "Epoch 17: Loss 0.416371\n",
      "Epoch 18: Loss 0.412977\n",
      "Epoch 19: Loss 0.409604\n",
      "Epoch 20: Loss 0.406250\n",
      "Epoch 21: Loss 0.403232\n",
      "Epoch 22: Loss 0.400331\n",
      "Epoch 23: Loss 0.397806\n",
      "Epoch 24: Loss 0.395222\n",
      "Epoch 25: Loss 0.392953\n",
      "Epoch 26: Loss 0.390763\n",
      "Epoch 27: Loss 0.388711\n",
      "Epoch 28: Loss 0.386837\n",
      "Epoch 29: Loss 0.385002\n",
      "Epoch 30: Loss 0.383464\n",
      "Epoch 31: Loss 0.381846\n"
     ]
    }
   ],
   "source": [
    "# 1. データセットの準備 (日本語 Wikipedia)\n",
    "dataset = load_dataset(\n",
    "    \"wikimedia/wikipedia\", \n",
    "    \"20231101.ja\", \n",
    "    split=\"train\",\n",
    "    streaming=True # メモリ節約のためストリーミングを推奨\n",
    ")\n",
    "\n",
    "def get_activations_loader(model, tokenizer, dataset, batch_size=32, max_tokens=100000):\n",
    "    \"\"\"\n",
    "    LLMから活性化値を抽出し、シャッフルされたデータローダーとして返す\n",
    "    \"\"\"\n",
    "    model.eval()\n",
    "    all_acts = []\n",
    "    token_count = 0\n",
    "    \n",
    "    # フックでデータを貯めるリスト\n",
    "    local_storage = []\n",
    "    def hook_fn(module, input, output):\n",
    "        # (batch, seq, dim) -> (batch * seq, dim)\n",
    "        local_storage.append(output.view(-1, output.shape[-1]).detach().cpu())\n",
    "\n",
    "    handle = model.model.layers[10].mlp.register_forward_hook(hook_fn)\n",
    "\n",
    "    print(\"Extracting activations from LLM...\")\n",
    "    for i, example in enumerate(dataset):\n",
    "        inputs = tokenizer(example[\"text\"], return_tensors=\"pt\", truncation=True, max_length=512).to(model.device)\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            model(**inputs)\n",
    "        \n",
    "        # 溜まったデータをall_actsに移動\n",
    "        if local_storage:\n",
    "            acts = torch.cat(local_storage, dim=0)\n",
    "            all_acts.append(acts)\n",
    "            token_count += acts.shape[0]\n",
    "            local_storage.clear()\n",
    "            \n",
    "        if token_count >= max_tokens:\n",
    "            break\n",
    "            \n",
    "    handle.remove()\n",
    "    \n",
    "    # 全データを結合してシャッフル\n",
    "    final_acts = torch.cat(all_acts, dim=0)\n",
    "    # インデックスをランダムに入れ替える\n",
    "    perm = torch.randperm(final_acts.shape[0])\n",
    "    final_acts = final_acts[perm]\n",
    "    \n",
    "    return DataLoader(final_acts, batch_size=batch_size, shuffle=True)\n",
    "\n",
    "# --- 学習の実行部分 ---\n",
    "\n",
    "# 10万トークン分のデータを抽出\n",
    "data_loader = get_activations_loader(model, tokenizer, dataset, batch_size=1024, max_tokens=100000)\n",
    "\n",
    "# SAEの初期化\n",
    "sae = SparseAutoencoder(d_in=2048, d_sae=32768, l1_coeff=0.001).to(\"cuda\")\n",
    "sae.to(torch.bfloat16)\n",
    "optimizer = torch.optim.Adam(sae.parameters(), lr=5e-4)\n",
    "\n",
    "print(\"Starting SAE Training...\")\n",
    "for epoch in range(32):\n",
    "    total_loss = 0\n",
    "    for batch in data_loader:\n",
    "        batch = batch.to(\"cuda\").to(torch.bfloat16)\n",
    "        \n",
    "        # 順伝播\n",
    "        _, loss, f = sae(batch)\n",
    "        \n",
    "        # 逆伝播\n",
    "        optimizer.zero_grad()\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        # 重要：デコーダの正規化\n",
    "        sae.set_decoder_norm_to_unit()\n",
    "        \n",
    "        total_loss += loss.item()\n",
    "    \n",
    "    print(f\"Epoch {epoch}: Loss {total_loss/len(data_loader):.6f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "81d7fc2d-3b4b-4c42-b661-dfc21a48ad85",
   "metadata": {},
   "outputs": [],
   "source": [
    "@torch.no_grad()\n",
    "def collect_interpretation_data(model, tokenizer, dataset, n_samples=10000):\n",
    "    \"\"\"\n",
    "    活性化値と、対応するトークンIDをセットで保存する\n",
    "    \"\"\"\n",
    "    model.eval()\n",
    "    all_acts = []\n",
    "    all_tokens = []\n",
    "    \n",
    "    # フックの再定義\n",
    "    local_acts = []\n",
    "    def hook_fn(m, i, o):\n",
    "        local_acts.append(o.view(-1, o.shape[-1]).detach().cpu())\n",
    "\n",
    "    handle = model.model.layers[10].mlp.register_forward_hook(hook_fn)\n",
    "\n",
    "    for i, example in enumerate(dataset):\n",
    "        inputs = tokenizer(example[\"text\"], return_tensors=\"pt\", truncation=True, max_length=128).to(model.device)\n",
    "        model(**inputs)\n",
    "        \n",
    "        # トークンIDも保存 (shape: [1, seq_len] -> [seq_len])\n",
    "        all_tokens.append(inputs.input_ids[0].cpu())\n",
    "        \n",
    "        if local_acts:\n",
    "            all_acts.append(torch.cat(local_acts, dim=0))\n",
    "            local_acts.clear()\n",
    "        \n",
    "        if len(torch.cat(all_tokens)) >= n_samples:\n",
    "            break\n",
    "\n",
    "    handle.remove()\n",
    "    return torch.cat(all_acts), torch.cat(all_tokens)\n",
    "\n",
    "def get_top_activating_tokens(sae, activations, tokens, tokenizer, unit_id, top_k=10):\n",
    "    sae.eval()\n",
    "    with torch.no_grad():\n",
    "        # SAEを通して特徴量 f を計算\n",
    "        # activations は [N, 2048]\n",
    "        # dtype を合わせるのを忘れずに！\n",
    "        acts_input = activations.to(\"cuda\").to(torch.bfloat16)\n",
    "        f = torch.nn.functional.relu(sae.encoder(acts_input - sae.b_dec))\n",
    "        \n",
    "        # 特定ユニットの全データにおける値を取得\n",
    "        unit_values = f[:, unit_id].cpu()\n",
    "        \n",
    "        # 値が大きい順にインデックスを取得\n",
    "        top_values, top_indices = torch.topk(unit_values, k=top_k)\n",
    "        \n",
    "        print(f\"--- Unit #{unit_id} Interpretation ---\")\n",
    "        for val, idx in zip(top_values, top_indices):\n",
    "            if val > 0:\n",
    "                token_text = tokenizer.decode([tokens[idx]])\n",
    "                # 前後の文脈も出すとより分かりやすい（今回は単語のみ）\n",
    "                print(f\"Activation: {val:.4f} | Token: '{token_text}'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "3e7e4a3f-fd64-448e-bc37-abcdfc3240dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- Unit #1024 Interpretation ---\n",
      "Activation: 0.0425 | Token: 'et'\n"
     ]
    }
   ],
   "source": [
    "# 1. データの収集 (1万トークン分)\n",
    "acts, tokens = collect_interpretation_data(model, tokenizer, dataset, n_samples=10000)\n",
    "\n",
    "# 2. 特定のユニットを調べてみる\n",
    "# 例えば、0番から順に見ていくのも手ですが、まずは「よく働いている」ユニットを探します\n",
    "# ここでは例として「ユニット #1024」を調査\n",
    "get_top_activating_tokens(sae, acts, tokens, tokenizer, unit_id=1026)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "258e9c46-1d05-403d-a633-bf028304f3a5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- Unit #1026 Interpretation ---\n",
      "Activation: 3.1562 | Token: ' License'\n",
      "Activation: 2.5000 | Token: '東'\n",
      "Activation: 2.0000 | Token: '西'\n",
      "Activation: 1.9219 | Token: '東'\n",
      "Activation: 1.8984 | Token: '東'\n",
      "Activation: 1.7266 | Token: 'マ'\n",
      "Activation: 1.6406 | Token: '西'\n",
      "Activation: 1.5859 | Token: '東'\n",
      "Activation: 1.3125 | Token: '�'\n",
      "Activation: 1.2578 | Token: '東'\n"
     ]
    }
   ],
   "source": [
    "get_top_activating_tokens(sae, acts, tokens, tokenizer, unit_id=1026)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3f92a7ae-ecf1-44a0-890c-20f7519a0f06",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- SAE Evaluation Metrics ---\n",
      "L0 (Active Units per Token): 94.79 / 32768\n",
      "FVU (Lower is better):       0.4277\n",
      "Explained Variance:          0.5723\n",
      "Dead Units:                  10772 (32.87%)\n"
     ]
    }
   ],
   "source": [
    "@torch.no_grad()\n",
    "def evaluate_sae(sae, activations):\n",
    "    sae.eval()\n",
    "    x = activations.to(\"cuda\").to(torch.bfloat16)\n",
    "    \n",
    "    # 順伝播\n",
    "    x_reconstruct, loss, f = sae(x)\n",
    "    \n",
    "    # 1. L0 Norm (スパース性)\n",
    "    # 各トークンで活性化したユニット数の平均\n",
    "    l0 = (f > 0).float().sum(dim=-1).mean().item()\n",
    "    \n",
    "    # 2. 再構成精度 (FVU)\n",
    "    per_token_mse = (x_reconstruct - x).pow(2).sum(dim=-1)\n",
    "    total_variance = (x - x.mean(dim=0)).pow(2).sum(dim=-1)\n",
    "    fvu = (per_token_mse.sum() / total_variance.sum()).item()\n",
    "    \n",
    "    # 3. Dead Units\n",
    "    # 全データを通して一度も活性化しなかったユニット\n",
    "    is_dead = (f <= 0).all(dim=0)\n",
    "    dead_unit_count = is_dead.sum().item()\n",
    "    dead_unit_pct = (dead_unit_count / sae.d_sae) * 100\n",
    "\n",
    "    print(f\"\\n--- SAE Evaluation Metrics ---\")\n",
    "    print(f\"L0 (Active Units per Token): {l0:.2f} / {sae.d_sae}\")\n",
    "    print(f\"FVU (Lower is better):       {fvu:.4f}\")\n",
    "    print(f\"Explained Variance:          {1 - fvu:.4f}\")\n",
    "    print(f\"Dead Units:                  {dead_unit_count} ({dead_unit_pct:.2f}%)\")\n",
    "    \n",
    "    return {\"l0\": l0, \"fvu\": fvu, \"dead_units\": dead_unit_pct}\n",
    "\n",
    "# 実行\n",
    "metrics = evaluate_sae(sae, acts)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "89ce9dc1-be2f-4822-b644-32393c12eb4a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "候補ユニット数: 349\n"
     ]
    }
   ],
   "source": [
    "@torch.no_grad()\n",
    "def find_interesting_units(sae, activations):\n",
    "    sae.eval()\n",
    "    acts_input = activations.to(\"cuda\").to(torch.bfloat16)\n",
    "    f = torch.nn.functional.relu(sae.encoder(acts_input - sae.b_dec))\n",
    "    \n",
    "    # 各ユニットが「0より大きい」値を出した回数をカウント\n",
    "    activation_counts = (f > 0).sum(dim=0).cpu()\n",
    "    \n",
    "    # 頻度が 0.1% 〜 1% 程度のユニットが、特定の「概念」を持っていることが多い\n",
    "    # (n_samples=10000 なら 10〜100回反応するユニット)\n",
    "    target_units = torch.where((activation_counts > 10) & (activation_counts < 100))[0]\n",
    "    return target_units.tolist()\n",
    "\n",
    "# 候補となるユニットのリストを取得\n",
    "candidate_units = find_interesting_units(sae, acts)\n",
    "print(f\"候補ユニット数: {len(candidate_units)}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "c270d4d2-0028-4edc-95b3-1eab760f35d4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🎉 レポートが正常に生成されました: sae_report.html\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.nn.functional as F\n",
    "\n",
    "@torch.no_grad()\n",
    "def generate_html_report(sae, activations, tokens, tokenizer, unit_ids, filename=\"sae_report.html\"):\n",
    "    sae.eval()\n",
    "    \n",
    "    # 1. すべてのデータに対する特徴量 f を一括計算 (メモリ節約のため小分けにするのもアリ)\n",
    "    acts_input = activations.to(\"cuda\").to(torch.bfloat16)\n",
    "    # f shape: [N, d_sae]\n",
    "    f = F.relu(sae.encoder(acts_input - sae.b_dec))\n",
    "    \n",
    "    html_content = [\"\"\"\n",
    "    <html>\n",
    "    <head>\n",
    "        <meta charset=\"utf-8\">\n",
    "        <style>\n",
    "            body { font-family: sans-serif; background-color: #f4f4f9; padding: 20px; }\n",
    "            .card { background: white; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; padding: 15px; }\n",
    "            .unit-title { color: #333; border-bottom: 2px solid #3498db; padding-bottom: 5px; }\n",
    "            .token-box { display: inline-block; padding: 4px 8px; margin: 3px; border-radius: 4px; border: 1px solid #ddd; }\n",
    "            .val-label { font-size: 0.8em; color: #666; display: block; }\n",
    "            .token-text { font-weight: bold; font-size: 1.1em; }\n",
    "        </style>\n",
    "    </head>\n",
    "    <body>\n",
    "        <h1>SAE Feature Interpretation Report (Qwen3-1.7B)</h1>\n",
    "    \"\"\"]\n",
    "\n",
    "    for uid in unit_ids:\n",
    "        unit_values = f[:, uid].cpu()\n",
    "        \n",
    "        # 活性化値が 0 より大きいものだけを対象に、Top 20を取得\n",
    "        top_k = min(20, (unit_values > 0).sum().item())\n",
    "        if top_k == 0:\n",
    "            continue\n",
    "            \n",
    "        top_values, top_indices = torch.topk(unit_values, k=top_k)\n",
    "        \n",
    "        html_content.append(f'<div class=\"card\">')\n",
    "        html_content.append(f'<h2 class=\"unit-title\">Unit #{uid} (Frequency: {top_k} samples shown)</h2>')\n",
    "        \n",
    "        for val, idx in zip(top_values, top_indices):\n",
    "            token_id = tokens[idx].item()\n",
    "            token_text = tokenizer.decode([token_id])\n",
    "            \n",
    "            # 活性化値の強さに応じて背景の青色を濃くする (最大値を基準に正規化)\n",
    "            opacity = min(1.0, val.item() / top_values[0].item())\n",
    "            bg_color = f\"rgba(52, 152, 219, {opacity * 0.6})\" \n",
    "            \n",
    "            html_content.append(f\"\"\"\n",
    "                <div class=\"token-box\" style=\"background-color: {bg_color};\">\n",
    "                    <span class=\"val-label\">{val.item():.3f}</span>\n",
    "                    <span class=\"token-text\">'{token_text}'</span>\n",
    "                </div>\n",
    "            \"\"\")\n",
    "        \n",
    "        html_content.append('</div>')\n",
    "\n",
    "    html_content.append(\"</body></html>\")\n",
    "    \n",
    "    with open(filename, \"w\", encoding=\"utf-8\") as f_out:\n",
    "        f_out.write(\"\\n\".join(html_content))\n",
    "    \n",
    "    print(f\"🎉 レポートが正常に生成されました: {filename}\")\n",
    "\n",
    "# --- 実行例 ---\n",
    "# 頻度が中程度のユニットを20個ほど抽出してレポートにする\n",
    "candidate_units = find_interesting_units(sae, acts) # 前のステップの関数\n",
    "generate_html_report(sae, acts, tokens, tokenizer, candidate_units[:100])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "58f5c5a6-3b64-43bf-b516-4ebcc62b1925",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==================== 比較実験 ====================\n",
      "プロンプト: 今日の晩御飯の献立を考えてください。\n",
      "操作ユニット: #3404 ('神' 関連)\n",
      "-------------------------------------------------\n",
      "【通常の状態】\n",
      "もちろん！今日の晩御飯の献立をいくつか提案します。ご希望の食材や調理法、ご飯の種類などがあれば、より具体的なメニューになります。\n",
      "\n",
      "---\n",
      "\n",
      "### 🍽️ 例：カジュアルな晩御飯（2人前）\n",
      "\n",
      "#### 🥘 ファーストディナー（メインディナー）\n",
      "- **味噌汁**（味噌、昆布、鯵や卵、人参、豆腐など）\n",
      "- **焼き魚**（タタキ、ローストチキン、サバなど）\n",
      "- **ご飯**（ご飯）\n",
      "\n",
      "#### 🥗 サイドドishes\n",
      "- **みかん**（フルーツ）\n",
      "- **ごはん**（ごはん）\n",
      "- **お味噌汁**（味噌、昆布、鯵など）\n",
      "\n",
      "---\n",
      "\n",
      "### 🍱 例：ヘルシーな晩御飯（2人前）\n",
      "\n",
      "#### 🥘 ファーストディナー\n",
      "- **豆腐のコンソメ煮**（豆腐、コンソメ、みりん、しいたけなど）\n",
      "- **昆布味噌汁**（昆布、味噌、鯵、人参など）\n",
      "- **ご飯**（ご飯）\n",
      "\n",
      "#### 🥗 サイドドishes\n",
      "- **ごはん**\n",
      "- **みかん**\n",
      "- **お豆腐のスープ\n",
      "-------------------------------------------------\n",
      "【ステアリング介入 (強度:60.0)】\n",
      "もちろんです！以下は、今日の晩御飯の献立を考えてください。この献立は、食事をするための簡単な方法で、さまざまな食材と料理を含んでいます。\n",
      "\n",
      "### 詳細な献立\n",
      "\n",
      "1. **おにぎり**  \n",
      "2. **おにぎり**（2つ）  \n",
      "3. **おにぎり**（3つ）  \n",
      "4. **おにぎり**（4つ）  \n",
      "5. **おにぎり**（5つ）  \n",
      "6. **おにぎり**（6つ）  \n",
      "7. **おにぎり**（7つ）  \n",
      "8. **おにぎり**（8つ）  \n",
      "9. **おにぎり**（9つ）  \n",
      "10. **おにぎり**（10つ）  \n",
      "11. **おにぎり**（11つ）  \n",
      "12. **おにぎり**（12つ）  \n",
      "13. **おにぎり**（13つ）  \n",
      "14. **おにぎり**（14つ）  \n",
      "15. **おにぎり**（15つ）  \n",
      "16. **おにぎり**（16つ）  \n",
      "17. **おにぎり**（17つ）  \n",
      "18. **おにぎり**（18つ）\n",
      "=================================================\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def compare_steering(model, tokenizer, sae, prompt, steer_unit_id, steer_strength=20.0, suppression_factor=0.0):\n",
    "    \"\"\"\n",
    "    通常の状態と、特定のSAEユニットを操作した状態の出力を比較する\n",
    "    \"\"\"\n",
    "    messages = [{\"role\": \"user\", \"content\": prompt}]\n",
    "    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True, enable_thinking=False)\n",
    "    inputs = tokenizer([text], return_tensors=\"pt\").to(model.device)\n",
    "    \n",
    "    # 生成のための共通設定\n",
    "    gen_kwargs = {\n",
    "        \"max_new_tokens\": 300,\n",
    "        \"do_sample\": True,\n",
    "        \"temperature\": 0.7,\n",
    "        \"top_p\": 0.9,\n",
    "        \"pad_token_id\": tokenizer.eos_token_id,\n",
    "    }\n",
    "\n",
    "    # --- 1. 通常の状態での生成 ---\n",
    "    # シード固定（比較を公平にするため）\n",
    "    torch.manual_seed(42)\n",
    "    with torch.no_grad():\n",
    "        output_normal = model.generate(**inputs, **gen_kwargs)\n",
    "    \n",
    "    text_normal = tokenizer.decode(output_normal[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)\n",
    "\n",
    "    # --- 2. ステアリング介入状態での生成 ---\n",
    "    def steering_hook(module, input, output):\n",
    "        # 1. SAEで今の思考（特徴量 f）を抽出\n",
    "        x_centered = output - sae.b_dec\n",
    "        f = torch.nn.functional.relu(sae.encoder(x_centered))\n",
    "        \n",
    "        # 2. 全ユニットを抑制係数で掛け合わせる（0.0なら全消去）\n",
    "        f_steered = f * suppression_factor\n",
    "        \n",
    "        # 3. ターゲットのユニットだけを高い値に固定\n",
    "        f_steered[:, :, steer_unit_id] = steer_strength\n",
    "        \n",
    "        # 4. 元の空間に戻す\n",
    "        return sae.decoder(f_steered) + sae.b_dec\n",
    "\n",
    "    handle = model.model.layers[10].mlp.register_forward_hook(steering_hook)\n",
    "\n",
    "    # 同じシードをセット（介入による差分だけを抽出するため）\n",
    "    torch.manual_seed(42)\n",
    "    with torch.no_grad():\n",
    "        output_steered = model.generate(**inputs, **gen_kwargs)\n",
    "    \n",
    "    text_steered = tokenizer.decode(output_steered[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)\n",
    "    handle.remove()\n",
    "\n",
    "    # --- 結果の表示 ---\n",
    "    print(f\"\\n{'='*20} 比較実験 {'='*20}\")\n",
    "    print(f\"プロンプト: {prompt}\")\n",
    "    print(f\"操作ユニット: #{steer_unit_id} ('神' 関連)\")\n",
    "    print(f\"{'-'*49}\")\n",
    "    print(f\"【通常の状態】\\n{text_normal.strip()}\")\n",
    "    print(f\"{'-'*49}\")\n",
    "    print(f\"【ステアリング介入 (強度:{steer_strength})】\\n{text_steered.strip()}\")\n",
    "    print(f\"{'='*49}\\n\")\n",
    "\n",
    "# --- 実行 ---\n",
    "# 全く関係ない話題を振ってみる\n",
    "compare_steering(model, tokenizer, sae, \"今日の晩御飯の献立を考えてください。\", steer_unit_id=3404, steer_strength=60.0, suppression_factor=0.0)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
